plugins { id 'com.android.application' }
android {
    namespace 'dev.pixelgba'
    compileSdk 35
    ndkVersion '27.2.12479018'
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    defaultConfig {
        applicationId 'dev.pixelgba'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.2'
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64' }
        externalNativeBuild { cmake { arguments '-DANDROID_STL=c++_static' } }
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    signingConfigs {
        release {
            if (project.hasProperty('pixelGbaKeystore')) {
                storeFile file(project.property('pixelGbaKeystore'))
                storePassword project.property('pixelGbaStorePassword')
                keyAlias project.property('pixelGbaKeyAlias')
                keyPassword project.property('pixelGbaKeyPassword')
            }
        }
    }
    buildTypes { release { signingConfig signingConfigs.release; minifyEnabled false } }
    externalNativeBuild { cmake { path 'src/main/cpp/CMakeLists.txt'; version '3.22.1' } }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
