cmake_minimum_required(VERSION 3.22.1)
project(pixelgba C)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(LIBMGBA_ONLY ON CACHE BOOL "" FORCE)
set(BUILD_STATIC ON CACHE BOOL "" FORCE)
set(BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(M_CORE_GB OFF CACHE BOOL "" FORCE)
foreach(flag BUILD_QT BUILD_SDL BUILD_GL BUILD_GLES2 BUILD_GLES3 USE_DEBUGGERS USE_FFMPEG USE_PNG USE_LIBZIP USE_MINIZIP USE_SQLITE3 USE_ELF USE_LUA USE_LZMA USE_DISCORD_RPC)
  set(${flag} OFF CACHE BOOL "" FORCE)
endforeach()
add_subdirectory(../../../../vendor/mgba ${CMAKE_CURRENT_BINARY_DIR}/mgba)
add_library(pixelgba SHARED bridge.c)
target_link_libraries(pixelgba mgba jnigraphics log)
target_link_options(pixelgba PRIVATE "-Wl,-z,max-page-size=16384")
